(function(){
'use strict';
var CT=window.CT;
if(!CT)return;
var baseRenderSync=CT.renderSync;
var baseRemoteLogin=CT.remoteLogin;
var endpointHint=new URLSearchParams(location.search).get('api')||localStorage.getItem('ct_remote_endpoint_hint')||'';

function workspace(){return CT.state.workspace}
function endpoint(){return String(workspace()&&workspace().sync&&workspace().sync.endpoint||'').replace(/\/$/,'')}
function token(){return workspace()&&workspace().sync&&workspace().sync.token||''}
function headers(extra){return Object.assign({Accept:'application/json',Authorization:token()?'Bearer '+token():''},extra||{})}
async function api(path,options){var response=await fetch(endpoint()+path,Object.assign({headers:headers(),credentials:'include'},options||{}));var data={};try{data=await response.json()}catch(error){}if(!response.ok){var err=new Error(data.detail||data.message||data.error||('HTTP '+response.status));err.status=response.status;throw err}return data}
function esc(value){return CT.esc(value==null?'':value)}
function date(value){return value?new Date(value).toLocaleString('es-AR'):'—'}

function applyEndpointHint(){if(!workspace())return;if(endpointHint&&!workspace().sync.endpoint){workspace().sync.endpoint=endpointHint.replace(/\/$/,'');localStorage.setItem('ct_remote_endpoint_hint',workspace().sync.endpoint);CT.saveWorkspace('Endpoint recibido por enlace',true)}if(workspace().sync.endpoint)localStorage.setItem('ct_remote_endpoint_hint',workspace().sync.endpoint)}

CT.remoteLogin=async function(username,password){var result=await baseRemoteLogin(username,password);try{await refreshIdentity();await CT.pullSync()}catch(error){workspace().sync.lastError=error.message}await refreshCollaboration();return result};

async function refreshIdentity(){if(!endpoint()||!token())return null;var data=await api('/api/me');workspace().sync.remoteUser=data.user||null;workspace().sync.organization=data.organization||null;CT.saveWorkspace('',true);return data}

async function refreshUsers(){var panel=CT.$('collabUsers');if(!panel)return;var user=workspace().sync.remoteUser;if(!user||user.role!=='admin'){panel.innerHTML='<div class="muted">Disponible para administradores.</div>';return}try{var data=await api('/api/admin/users');panel.innerHTML=(data.users||[]).map(function(item){return '<article class="device-card"><div class="row"><div><strong>'+esc(item.username)+'</strong><small>Último acceso: '+date(item.lastLoginAt)+'</small></div><span class="badge '+(item.active?'official':'review')+'">'+(item.active?'Activo':'Inactivo')+'</span></div><div class="field-grid two compact"><label>Rol<select data-collab-role="'+esc(item.id)+'"><option value="admin">Administrador</option><option value="editor">Editor</option><option value="viewer">Sólo lectura</option></select></label><label class="check-row"><input type="checkbox" data-collab-active="'+esc(item.id)+'" '+(item.active?'checked':'')+'> Cuenta activa</label></div><button type="button" data-collab-save-user="'+esc(item.id)+'">Guardar usuario</button></article>'}).join('')||'<div class="muted">No hay usuarios.</div>';(data.users||[]).forEach(function(item){var select=panel.querySelector('[data-collab-role="'+CSS.escape(item.id)+'"]');if(select)select.value=item.role})}catch(error){panel.innerHTML='<div class="form-error">'+esc(error.message)+'</div>'}}

async function refreshSessions(){var panel=CT.$('collabSessions');if(!panel)return;try{var data=await api('/api/sessions');panel.innerHTML=(data.sessions||[]).map(function(item){return '<article class="device-card"><div class="row"><div><strong>'+(item.current?'Este dispositivo':esc(item.deviceId||'Dispositivo'))+'</strong><small>'+date(item.createdAt)+' · vence '+date(item.expiresAt)+'</small></div><span class="badge '+(item.revokedAt?'review':'official')+'">'+(item.revokedAt?'Revocada':'Activa')+'</span></div><small>'+esc(item.userAgent||'')+'</small>'+(!item.revokedAt?'<button type="button" data-collab-revoke="'+esc(item.id)+'">'+(item.current?'Cerrar esta sesión':'Revocar dispositivo')+'</button>':'')+'</article>'}).join('')||'<div class="muted">No hay sesiones registradas.</div>'}catch(error){panel.innerHTML='<div class="form-error">'+esc(error.message)+'</div>'}}

async function refreshHistory(){var panel=CT.$('collabHistory');if(!panel)return;try{var data=await api('/api/history');panel.innerHTML=(data.history||[]).map(function(item){return '<article class="device-card"><div class="row"><div><strong>Revisión '+esc(item.revision)+'</strong><small>'+date(item.created_at||item.createdAt)+' · '+esc(item.actor_username||'sistema')+'</small></div><button type="button" data-collab-restore="'+esc(item.revision)+'">Restaurar</button></div></article>'}).join('')||'<div class="muted">Todavía no hay versiones anteriores.</div>'}catch(error){panel.innerHTML='<div class="form-error">'+esc(error.message)+'</div>'}}

async function refreshCollaboration(){if(!workspace())return;applyEndpointHint();var user=workspace().sync.remoteUser,identity=CT.$('collabIdentity');document.body.classList.toggle('remote-viewer',!!(user&&user.role==='viewer'));if(identity){var org=workspace().sync.organization;identity.innerHTML=user?'<div><i class="sync-dot ok"></i><strong>'+esc(user.username)+'</strong> · '+esc(user.role)+'</div><div>Espacio compartido: '+esc(org&&org.name||'Corrientes Territorial')+'</div>':'<div><i class="sync-dot"></i>Conectá una cuenta remota para habilitar colaboración.</div>'}if(!user){['collabUsers','collabSessions','collabHistory'].forEach(function(id){var el=CT.$(id);if(el)el.innerHTML='<div class="muted">Sin sesión remota.</div>'});return}await Promise.all([refreshUsers(),refreshSessions(),refreshHistory()])}

CT.renderSync=function(){baseRenderSync();if(!workspace())return;applyEndpointHint();var endpointInput=CT.$('syncEndpoint');if(endpointInput&&endpointHint&&!endpointInput.value)endpointInput.value=endpointHint;var warning=CT.$('viewerWarning'),user=workspace().sync.remoteUser;if(warning)warning.classList.toggle('hidden',!(user&&user.role==='viewer'));var org=workspace().sync.organization,identity=CT.$('collabIdentity');if(identity&&user)identity.innerHTML='<div><i class="sync-dot ok"></i><strong>'+esc(user.username)+'</strong> · '+esc(user.role)+'</div><div>Espacio compartido: '+esc(org&&org.name||'Corrientes Territorial')+'</div>'};

function install(){if(!workspace()){setTimeout(install,100);return}applyEndpointHint();var view=CT.$('view-sync');if(!view||CT.$('collaborationPanel'))return;var panel=document.createElement('div');panel.id='collaborationPanel';panel.innerHTML='<article class="panel"><div class="section-heading"><div><h2>Colaboración</h2><p>Usuarios, organización y permisos</p></div><button id="refreshCollaboration" type="button" class="small-button">Actualizar</button></div><div id="collabIdentity" class="stack small"></div><div id="viewerWarning" class="form-error hidden">Esta cuenta es de sólo lectura. Puede consultar y descargar, pero el servidor rechazará modificaciones.</div></article><article class="panel"><h2>Usuarios autorizados</h2><div id="collabUsers" class="stack"></div></article><article class="panel"><h2>Dispositivos conectados</h2><div id="collabSessions" class="stack"></div></article><article class="panel"><h2>Historial remoto</h2><p class="muted">Cada sincronización conserva una versión recuperable.</p><div id="collabHistory" class="stack"></div></article>';view.appendChild(panel);CT.$('refreshCollaboration').onclick=refreshCollaboration;document.addEventListener('click',async function(event){var target=event.target.closest('[data-collab-save-user],[data-collab-revoke],[data-collab-restore]');if(!target)return;try{if(target.dataset.collabSaveUser){var id=target.dataset.collabSaveUser,role=CT.$('collabUsers').querySelector('[data-collab-role="'+CSS.escape(id)+'"]').value,active=CT.$('collabUsers').querySelector('[data-collab-active="'+CSS.escape(id)+'"]').checked;await api('/api/admin/users/'+encodeURIComponent(id),{method:'PATCH',headers:headers({'Content-Type':'application/json'}),body:JSON.stringify({role:role,active:active})});CT.toast('Usuario actualizado.');await refreshUsers();return}if(target.dataset.collabRevoke){await api('/api/sessions/'+encodeURIComponent(target.dataset.collabRevoke),{method:'DELETE',headers:headers()});CT.toast('Sesión revocada.');await refreshSessions();return}if(target.dataset.collabRestore){if(!confirm('¿Restaurar esta revisión para todo el equipo?'))return;var data=await api('/api/history/'+encodeURIComponent(target.dataset.collabRestore)+'/restore',{method:'POST',headers:headers({'Content-Type':'application/json'}),body:'{}'});if(data.workspace){CT.mergeSyncedWorkspace(Object.assign({},data.workspace,{sync:Object.assign({},data.workspace.sync||{},{revision:data.revision})}))}CT.toast('Versión restaurada.');await refreshHistory()}}catch(error){CT.toast('No se pudo completar: '+error.message)}});refreshCollaboration()}

document.addEventListener('DOMContentLoaded',install);
})();
