(function(){
'use strict';
var CT=window.CT;
function beginSession(user){CT.state.user=user;localStorage.setItem(CT.SESSION_KEY,user);CT.loadWorkspace();CT.applySettings();CT.$('loginView').classList.add('hidden');CT.$('app').classList.remove('hidden');CT.$('accountButton').textContent=user.slice(0,2).toUpperCase();CT.populateControls();var hash=location.hash.replace('#','');CT.activateView(CT.VIEW_TITLES[hash]?hash:'home');CT.renderAll()}
function showLogin(){CT.state.user='';CT.$('boot').classList.add('hidden');CT.$('app').classList.add('hidden');CT.$('loginView').classList.remove('hidden');CT.$('loginUser').value='Ivo';CT.$('loginPassword').value='';setTimeout(function(){CT.$('loginPassword').focus()},80)}
function initSession(){var user=localStorage.getItem(CT.SESSION_KEY)||localStorage.getItem(CT.OLD_SESSION_KEY);CT.$('boot').classList.add('hidden');if(user)beginSession(user);else showLogin()}
function resetRelationForm(){CT.$('relationId').value='';CT.$('relationshipFormTitle').textContent='Nueva relación';CT.$('cancelRelationEdit').classList.add('hidden');CT.$('relationshipForm').reset();if(CT.$('relationTo').options.length>1)CT.$('relationTo').selectedIndex=1;CT.$('relationConfidence').value='3'}
function editRelation(id){var r=(CT.state.workspace.relations||[]).find(function(x){return x.id===id});if(!r)return;CT.$('relationId').value=r.id;CT.$('relationFrom').value=r.fromId;CT.$('relationTo').value=r.toId;CT.$('relationType').value=r.type;CT.$('relationEvidence').value=r.evidence;CT.$('relationConfidence').value=r.confidence||3;CT.$('relationSource').value=r.source||'';CT.$('relationNote').value=r.note||'';CT.$('relationshipFormTitle').textContent='Editar relación';CT.$('cancelRelationEdit').classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'})}
function resetAgendaForm(){CT.$('agendaId').value='';CT.$('agendaFormTitle').textContent='Nueva actividad';CT.$('cancelAgendaEdit').classList.add('hidden');CT.$('agendaForm').reset()}
function editAgenda(id){var a=(CT.state.workspace.agenda||[]).find(function(x){return x.id===id});if(!a)return;CT.$('agendaId').value=a.id;CT.$('agendaTitle').value=a.title||'';CT.$('agendaDate').value=a.date||'';CT.$('agendaType').value=a.type||'followup';CT.$('agendaTerritory').value=a.territory||'';CT.$('agendaPerson').value=a.personId||'';CT.$('agendaNote').value=a.note||'';CT.$('agendaFormTitle').textContent='Editar actividad';CT.$('cancelAgendaEdit').classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'})}
function exportCandidates(){var rows=[['Persona','Cargo','Jurisdicción','Categoría','Orden','Fuente']];(CT.state.candidates.nominations||[]).forEach(function(n){rows.push([CT.personName(n.personId),n.office,n.jurisdiction,CT.categoryFor(n),n.order||'',n.sourceUrl||''])});CT.download('candidaturas-lla-corrientes-2025.csv','\ufeff'+CT.csv(rows),'text/csv;charset=utf-8')}
function exportResults(){var rows=[['Jurisdicción','Nivel','Categoría','Votos LLA','Votos válidos','Porcentaje','Fuente']];(CT.state.results.llaResults||[]).forEach(function(r){rows.push([r.jurisdiction,r.jurisdictionType,r.category,r.votes,r.validVotes,resultValue(r),r.sourceUrl||''])});CT.download('resultados-lla-corrientes-2025.csv','\ufeff'+CT.csv(rows),'text/csv;charset=utf-8')}
function resultValue(r){return Number(r&&(r.percentageDisplayed!=null?r.percentageDisplayed:r.percentage)||0)}
function exportRelations(){var rows=[['Desde','Tipo','Hacia','Evidencia','Confianza','Fuente','Nota','Actualizado']];(CT.state.workspace.relations||[]).forEach(function(r){rows.push([CT.personName(r.fromId),r.type,CT.personName(r.toId),r.evidence,r.confidence,r.source||'',r.note||'',r.updatedAt||''])});CT.download('relaciones-'+CT.state.user+'.csv','\ufeff'+CT.csv(rows),'text/csv;charset=utf-8')}
function exportAgenda(){var rows=[['Título','Fecha','Tipo','Estado','Territorio','Persona','Nota']];(CT.state.workspace.agenda||[]).forEach(function(a){rows.push([a.title,a.date||'',a.type,a.status,a.territory||'',a.personId?CT.personName(a.personId):'',a.note||''])});CT.download('agenda-'+CT.state.user+'.csv','\ufeff'+CT.csv(rows),'text/csv;charset=utf-8')}
function openGlobalSearch(){CT.$('globalSearch').classList.remove('hidden');CT.$('globalSearchInput').value='';CT.renderGlobalSearch();setTimeout(function(){CT.$('globalSearchInput').focus()},60)}
function closeGlobalSearch(){CT.$('globalSearch').classList.add('hidden')}
function handleRecent(type,id){if(type==='person'){CT.openPerson(id);return}if(type==='territory'){CT.$('territorySelect').value=id;CT.activateView('territories');return}if(type==='agenda'){CT.activateView('agenda')}}
function bindEvents(){CT.$('loginForm').addEventListener('submit',function(event){event.preventDefault();var user=CT.$('loginUser').value.trim(),password=CT.$('loginPassword').value;if(!user||password!==user){CT.$('loginError').textContent='El usuario y la contraseña deben ser iguales.';return}CT.$('loginError').textContent='';beginSession(user)});
CT.$('globalSearchButton').onclick=openGlobalSearch;CT.$('globalSearchClose').onclick=closeGlobalSearch;CT.$('globalSearchInput').oninput=CT.renderGlobalSearch;CT.$('sheetClose').onclick=CT.closeSheet;CT.$('sheetBackdrop').onclick=CT.closeSheet;CT.$('accountButton').onclick=function(){CT.activateView('data')};
CT.$('refreshData').onclick=function(){CT.loadData(true)};CT.$('homeCategory').onchange=CT.renderHome;
['mapLevel','mapCategory'].forEach(function(id){CT.$(id).onchange=function(){CT.state.map.selected='';CT.drawMap()}});CT.$('mapSearch').oninput=CT.drawMap;CT.$('mapZoomIn').onclick=function(){CT.state.map.scale=Math.min(3,CT.state.map.scale+.25);CT.applyMapTransform()};CT.$('mapZoomOut').onclick=function(){CT.state.map.scale=Math.max(.65,CT.state.map.scale-.25);CT.applyMapTransform()};CT.$('mapReset').onclick=function(){CT.state.map={scale:1,x:0,y:0,selected:''};CT.drawMap()};CT.$('mapRanking').onclick=CT.renderMapRanking;
['peopleSearch','peopleJurisdiction','peopleRole','peopleSort','peopleFavoritesOnly'].forEach(function(id){var el=CT.$(id);el.addEventListener(id==='peopleSearch'?'input':'change',CT.renderPeople)});CT.$('territorySelect').onchange=CT.renderTerritory;CT.$('favoriteTerritory').onclick=function(){var name=CT.$('territorySelect').value;CT.toggleFavoriteTerritory(name);CT.renderTerritory()};CT.$('openCompare').onclick=function(){CT.$('compareA').value=CT.$('territorySelect').value;CT.activateView('compare')};CT.$('openTerritoryMap').onclick=function(){CT.$('mapLevel').value='municipality';CT.state.map.selected=CT.canonJur(CT.$('territorySelect').value);CT.activateView('map')};['compareA','compareB','compareCategory'].forEach(function(id){CT.$(id).onchange=CT.renderCompare});
['networkTypeFilter','networkEvidenceFilter'].forEach(function(id){CT.$(id).onchange=CT.renderNetwork});CT.$('networkSearch').oninput=CT.renderNetwork;CT.$('cancelRelationEdit').onclick=resetRelationForm;CT.$('relationshipForm').onsubmit=function(event){event.preventDefault();var from=CT.$('relationFrom').value,to=CT.$('relationTo').value;if(!from||!to||from===to){CT.toast('Elegí dos personas diferentes.');return}CT.upsertRelation({id:CT.$('relationId').value||undefined,fromId:from,toId:to,type:CT.$('relationType').value,evidence:CT.$('relationEvidence').value,confidence:Number(CT.$('relationConfidence').value||3),source:CT.$('relationSource').value.trim(),note:CT.$('relationNote').value.trim()});resetRelationForm();CT.renderNetwork();CT.toast('Relación guardada.')};
CT.$('cancelAgendaEdit').onclick=resetAgendaForm;CT.$('agendaForm').onsubmit=function(event){event.preventDefault();CT.upsertAgenda({id:CT.$('agendaId').value||undefined,title:CT.$('agendaTitle').value.trim(),date:CT.$('agendaDate').value,type:CT.$('agendaType').value,territory:CT.$('agendaTerritory').value,personId:CT.$('agendaPerson').value,note:CT.$('agendaNote').value.trim()});resetAgendaForm();CT.renderAgenda();CT.toast('Actividad guardada.')};['agendaStatusFilter','agendaTypeFilter'].forEach(function(id){CT.$(id).onchange=CT.renderAgenda});['sourceStatusFilter','sourceTypeFilter'].forEach(function(id){CT.$(id).onchange=CT.renderSources});CT.$('sourceSearch').oninput=CT.renderSources;
CT.$('exportJson').onclick=CT.exportWorkspace;CT.$('exportCandidatesCsv').onclick=exportCandidates;CT.$('exportResultsCsv').onclick=exportResults;CT.$('exportRelationsCsv').onclick=exportRelations;CT.$('exportAgendaCsv').onclick=exportAgenda;CT.$('importJson').onchange=async function(event){try{var file=event.target.files&&event.target.files[0];if(!file)return;await CT.importWorkspace(file);CT.populateControls();CT.renderAll();CT.toast('Respaldo importado.')}catch(error){CT.toast('No se pudo importar: '+error.message)}event.target.value=''};CT.$('themeSetting').onchange=function(){CT.updateSettings({theme:this.value})};CT.$('fontSetting').onchange=function(){CT.updateSettings({font:this.value})};CT.$('compactSetting').onchange=function(){CT.updateSettings({compact:this.checked})};CT.$('lockButton').onclick=showLogin;CT.$('logoutButton').onclick=function(){localStorage.removeItem(CT.SESSION_KEY);showLogin()};CT.$('clearRecents').onclick=function(){CT.state.workspace.recent=[];CT.saveWorkspace('Actividad reciente eliminada');CT.renderHome()};CT.$('resetWorkspace').onclick=function(){if(confirm('¿Restablecer todas las notas, relaciones, favoritos y agenda de este usuario?')){CT.resetWorkspace();CT.populateControls();CT.renderAll();CT.toast('Espacio privado restablecido.')}};
CT.qa('[data-target]').forEach(function(button){button.onclick=function(){CT.activateView(button.dataset.target)}});document.addEventListener('click',function(event){var target=event.target.closest('button,[data-person],[data-open-view],[data-open-url],[data-open-territory],[data-open-map-territory],[data-fav-person],[data-fav-territory],[data-save-person],[data-save-territory],[data-edit-relation],[data-delete-relation],[data-toggle-agenda],[data-edit-agenda],[data-delete-agenda],[data-verify-source],[data-recent-type],[data-global-type]');if(!target)return;if(target.dataset.openView){CT.activateView(target.dataset.openView);return}if(target.dataset.openUrl){CT.openSource(target.dataset.openUrl);return}if(target.dataset.person){CT.openPerson(target.dataset.person);return}if(target.dataset.favPerson){CT.toggleFavoritePerson(target.dataset.favPerson);CT.renderPeople();if(!CT.$('bottomSheet').classList.contains('hidden'))CT.openPerson(target.dataset.favPerson);return}if(target.dataset.favTerritory){CT.toggleFavoriteTerritory(target.dataset.favTerritory);CT.drawMap();return}if(target.dataset.openTerritory){CT.$('territorySelect').value=target.dataset.openTerritory;CT.activateView('territories');return}if(target.dataset.openMapTerritory){CT.openMapTerritory(target.dataset.openMapTerritory);return}if(target.dataset.savePerson){CT.setPersonTags(target.dataset.savePerson,CT.$('personTagsEdit').value);CT.setPersonNote(target.dataset.savePerson,CT.$('personNoteEdit').value);CT.toast('Ficha local guardada.');return}if(target.dataset.saveTerritory){var name=target.dataset.saveTerritory;CT.setTerritoryMeta(name,{priority:CT.$('territoryPriority').value,status:CT.$('territoryStatus').value,owner:CT.$('territoryOwner').value.trim()});CT.setTerritoryTags(name,CT.$('territoryTagsEdit').value);CT.setTerritoryNote(name,CT.$('territoryNoteEdit').value);CT.renderTerritory();CT.toast('Evaluación territorial guardada.');return}if(target.dataset.editRelation){editRelation(target.dataset.editRelation);return}if(target.dataset.deleteRelation){if(confirm('¿Eliminar esta relación?'))CT.deleteRelation(target.dataset.deleteRelation);return}if(target.dataset.toggleAgenda){CT.toggleAgenda(target.dataset.toggleAgenda);CT.renderAgenda();return}if(target.dataset.editAgenda){editAgenda(target.dataset.editAgenda);return}if(target.dataset.deleteAgenda){if(confirm('¿Eliminar esta actividad?'))CT.deleteAgenda(target.dataset.deleteAgenda);return}if(target.dataset.verifySource){var key=target.dataset.verifySource,status=CT.sourceStatus(key)==='verified'?'pending':'verified';CT.reviewSource(key,status,'');CT.renderSources();return}if(target.dataset.recentType){handleRecent(target.dataset.recentType,target.dataset.recentId);return}if(target.dataset.globalType){var type=target.dataset.globalType,id=target.dataset.globalId;closeGlobalSearch();handleRecent(type,id);return}});
window.addEventListener('hashchange',function(){var view=location.hash.replace('#','');if(CT.VIEW_TITLES[view])CT.activateView(view)});window.addEventListener('online',function(){CT.record('Conexión recuperada');CT.renderDiagnostics()});window.addEventListener('offline',function(){CT.record('Sin conexión');CT.renderDiagnostics()})}
async function boot(){bindEvents();initSession();await CT.loadData(false);if(CT.state.workspace){CT.populateControls();CT.renderAll()}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
